### ISSUE TITLE
`offline` not working when using linguist-js as library

### ISSUE THREAD

**Issue by hstaudacher** [Nixinova/LinguistJS#18] opened 2023-01-12 16:43 UTC
I just started linguist-js as library and it's pretty nice :). I have discovered that using it out of a unit test e.g. mocha with the `offline` option set to `true` will lead to an error. For me the message is:

```ts
Error: ENOENT: no such file or directory, open '{MY_PATH}/ext/languages.yml'
```
where `{MY_PATH}` is the path to my `../project`.  It seems the loading via `../../` in [loadData](https://github.com/Nixinova/LinguistJS/blob/main/src/helpers/load-data.ts#L20) is not made for this kind of use. It would be very cool if this could be stabilized.

**Comment by hstaudacher** [comment] 2023-01-12 17:12
Thinking about this more I think a valid enhancement could be to allow passing an own set of linguist yml files. Raw or already parsed would be another option.

With this the library would be decoupled from the actual yml files which means a consumer could update the yml files without the need for this library to create a new release.

What do you think?

**Comment by Nixinova** [comment] 2023-01-17 07:24
Hi, thanks for the report.

> I have discovered that using it out of a unit test e.g. mocha with the offline option set to true will lead to an error.

Do you have a reproduction for this issue? Because the `offline` option works fine when I make a repo with this as `index`:
```mjs
import linguist from 'linguist-js';

const data = await linguist('.', { offline: true });

console.debug(data);
```
```json5
//C:\Users\user\AppData\Local\Temp\20230117>node index.mjs
{
  files: {
    count: 2,
    bytes: 367,
    results: {
      'C:/Users/user/AppData/Local/Temp/20230117/index.mjs': 'JavaScript',
      'C:/Users/user/AppData/Local/Temp/20230117/package.json': 'JSON'
    }
  },
  languages: {
    count: 2,
    bytes: 367,
    results: { JavaScript: [Object], JSON: [Object] }
  },
  unknown: { count: 0, bytes: 0, extensions: {}, filenames: {} }
}
```
And I did confirm the offline option was working properly by going on airplane mode, heh.

**Comment by Nixinova** [comment] 2023-01-17 07:27
> Thinking about this more I think a valid enhancement could be to allow passing an own set of linguist yml files. Raw or already parsed would be another option.
> With this the library would be decoupled from the actual yml files which means a consumer could update the yml files without the need for this library to create a new release.

Hm, this seems like it would have a lot of overhead for not a lot of benefit. Having lag from the upstream yml files doesn't seem like a big deal - if you want the very latest you can use online mode, if you want stability and insurance that it will work correctly you can use offline mode. I don't feel like allowing custom yaml files would be too useful a feature. Do you have a use case where custom yml files would be a useful feature to have?

**Comment by Nixinova** [comment] 2023-03-13 04:54
@hstaudacher can you provide more information about how to reproduce this issue?

**Comment by Nixinova** [comment] 2023-07-26 06:10
Using Linguist in a Mocha test seems to work just fine:

```js
const assert = require('assert');
const linguist = require('linguist-js');
describe('Linguist', function () {
    describe('issue#18', function () {
        it('should linguist()', async function () {
            const data = await linguist('.', { offline: true });
            assert.equal(data.languages.count, 2);
        })
    });
});

```
```cmd
>npx mocha


  Linguist
    issue#18
      √ should linguist() (134ms)


  1 passing (142ms)
```

Closing as not repoducable.

**Closed by Nixinova** 2023-07-26 06:10 UTC
Labels: bug, enhancement, node usage, awaiting response
